services:

  server:
    build: ./domain
    image: whenderson/equion_server
    restart: always
    expose:
      - 80
    depends_on:
      - db
    environment:
      EQUION_DATABASE_URL: "mysql://root:hunter2@db:3306/equion"

  db:
    image: mysql:latest
    restart: always
    expose:
      - 3306
    volumes:
      - ./domain/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hunter2

  voice:
    image: peerjs/peerjs-server
    restart: always
    expose:
      - 9000
    command: [ "--port", "9000", "--path", "/", "--proxied" ]

  web:
    build: ./axiom
    image: whenderson/equion_web
    entrypoint: sh -c "cp -R /app/public/* /var/www/html"
    volumes:
      - website:/var/www/html

  download_manager:
    build: ./matrix
    image: whenderson/equion_download_manager
    restart: always
    expose:
      - 80
    volumes:
      - releaseData:/releaseData
    environment:
      EQUION_MATRIX_DATA_DIR: "/releaseData"

  gateway:
    image: nginx:latest
    restart: always
    depends_on:
      - download_manager
      - server
      - voice
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/cert
      - website:/var/www/html
      - releaseData:/releaseData

volumes:
  data:
  website:
  releaseData:
