[package]
name = "equion_server"
version = "0.1.0"
edition = "2021"

[dependencies]
humphrey = "^0.6.3"
humphrey_ws = "^0.3.4"
humphrey_json = "^0.1.1"
mysql = "^22.1.0"
uuid = { version = "^1.0.0", features = ["v4"] }
argon2 = "^0.3.0"
chrono = "^0.4.19"
base64 = "^0.13.0"